export const randomfirstname = Math.random().toString(36).substring(2);
export const randomsurname = Math.random().toString(36).substring(2);
export const randomcompanyname = Math.random().toString(36).substring(2);
export const randomindustry = Math.random().toString(36).substring(2);
export const randomjob = Math.random().toString(36).substring(2);
export const firstname = 'input[name="firstname"]'
export const surname = 'input[name="surname"]'
export const  email = 'input[name="email"]'
export const job = 'input[name="job"]'
export const companyname = 'input[name="companyname"]'
export const industry = 'input[name="industry"]'
export const location = '#mui-component-select-location'
export const numberofemployee = '#mui-component-select-numberofemployees'
export const password = 'input[name="password"]'
export const confirmpassword = 'input[name="confirmpassword"]'
export const acceptterms = 'input[name="acceptTerms"]'
export const submit = 'button[type="submit"]'
